### ISSUE TITLE
system assigns duplicate IGSN for different samples

### ISSUE THREAD

**Issue by smrgeoinfo** [iedadata/sesar#27]
The system assigned an IGSN to a sample using Individual Sample Registration that was already assigned to the Parent IGSN. This is related to the fact that igsn_to_int is null in the database for the parent sample. 
Auto IGSN assignment algorithm needs to be reviewed and fixed. 
[reported by Megan via e-mail]
Some detail on how to reproduce the problem would be useful

**Comment by smrgeoinfo** [comment]
task http://task.ldeo-grg.org/issues/306 created in Redmine for fix.

**Comment by lulin-song** [comment]
fixed in v7.0.2 release
